// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/modules/listener/listener.proto

package listener

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NoParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoParameter) Reset() {
	*x = NoParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoParameter) ProtoMessage() {}

func (x *NoParameter) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoParameter.ProtoReflect.Descriptor instead.
func (*NoParameter) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{0}
}

type ServicesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Items []*ServicesItems `protobuf:"bytes,1,rep,name=Items,proto3" json:"Items,omitempty"`
}

func (x *ServicesResponse) Reset() {
	*x = ServicesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesResponse) ProtoMessage() {}

func (x *ServicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesResponse.ProtoReflect.Descriptor instead.
func (*ServicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{1}
}

func (x *ServicesResponse) GetItems() []*ServicesItems {
	if x != nil {
		return x.Items
	}
	return nil
}

type ParameterFunction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Send string `protobuf:"bytes,2,opt,name=Send,proto3" json:"Send,omitempty"`
	Recv string `protobuf:"bytes,3,opt,name=Recv,proto3" json:"Recv,omitempty"`
}

func (x *ParameterFunction) Reset() {
	*x = ParameterFunction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ParameterFunction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParameterFunction) ProtoMessage() {}

func (x *ParameterFunction) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParameterFunction.ProtoReflect.Descriptor instead.
func (*ParameterFunction) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{2}
}

func (x *ParameterFunction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ParameterFunction) GetSend() string {
	if x != nil {
		return x.Send
	}
	return ""
}

func (x *ParameterFunction) GetRecv() string {
	if x != nil {
		return x.Recv
	}
	return ""
}

type ServicesItems struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Service        string               `protobuf:"bytes,1,opt,name=Service,proto3" json:"Service,omitempty"`
	Method         string               `protobuf:"bytes,2,opt,name=Method,proto3" json:"Method,omitempty"`
	FullMethod     string               `protobuf:"bytes,3,opt,name=FullMethod,proto3" json:"FullMethod,omitempty"`
	Input          []*ParameterFunction `protobuf:"bytes,4,rep,name=Input,proto3" json:"Input,omitempty"`
	Output         []*ParameterFunction `protobuf:"bytes,5,rep,name=Output,proto3" json:"Output,omitempty"`
	ServerStream   bool                 `protobuf:"varint,6,opt,name=ServerStream,proto3" json:"ServerStream,omitempty"`
	ClientStream   bool                 `protobuf:"varint,7,opt,name=ClientStream,proto3" json:"ClientStream,omitempty"`
	ProtoReference string               `protobuf:"bytes,8,opt,name=ProtoReference,proto3" json:"ProtoReference,omitempty"`
}

func (x *ServicesItems) Reset() {
	*x = ServicesItems{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesItems) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesItems) ProtoMessage() {}

func (x *ServicesItems) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesItems.ProtoReflect.Descriptor instead.
func (*ServicesItems) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{3}
}

func (x *ServicesItems) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *ServicesItems) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ServicesItems) GetFullMethod() string {
	if x != nil {
		return x.FullMethod
	}
	return ""
}

func (x *ServicesItems) GetInput() []*ParameterFunction {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ServicesItems) GetOutput() []*ParameterFunction {
	if x != nil {
		return x.Output
	}
	return nil
}

func (x *ServicesItems) GetServerStream() bool {
	if x != nil {
		return x.ServerStream
	}
	return false
}

func (x *ServicesItems) GetClientStream() bool {
	if x != nil {
		return x.ClientStream
	}
	return false
}

func (x *ServicesItems) GetProtoReference() string {
	if x != nil {
		return x.ProtoReference
	}
	return ""
}

type Discovery struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Enable   bool   `protobuf:"varint,1,opt,name=Enable,proto3" json:"Enable,omitempty" yaml:"enable"`    // @gotags: yaml:"enable"
	Driver   string `protobuf:"bytes,2,opt,name=Driver,proto3" json:"Driver,omitempty" yaml:"driver"`     // @gotags: yaml:"driver"
	Exchange string `protobuf:"bytes,3,opt,name=Exchange,proto3" json:"Exchange,omitempty" yaml:"exchange"` // @gotags: yaml:"exchange"
}

func (x *Discovery) Reset() {
	*x = Discovery{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Discovery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Discovery) ProtoMessage() {}

func (x *Discovery) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Discovery.ProtoReflect.Descriptor instead.
func (*Discovery) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{4}
}

func (x *Discovery) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

func (x *Discovery) GetDriver() string {
	if x != nil {
		return x.Driver
	}
	return ""
}

func (x *Discovery) GetExchange() string {
	if x != nil {
		return x.Exchange
	}
	return ""
}

type ServicesInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Version   string `protobuf:"bytes,1,opt,name=Version,proto3" json:"version,omitempty"`     // @gotags: json:"version,omitempty"
	GitCommit string `protobuf:"bytes,2,opt,name=GitCommit,proto3" json:"gitCommit,omitempty"` // @gotags: json:"gitCommit,omitempty"
	GoVersion string `protobuf:"bytes,3,opt,name=GoVersion,proto3" json:"goVersion,omitempty"` // @gotags: json:"goVersion,omitempty"
	Compiler  string `protobuf:"bytes,4,opt,name=Compiler,proto3" json:"compiler,omitempty"`   // @gotags: json:"compiler,omitempty"
	BuildTime string `protobuf:"bytes,5,opt,name=BuildTime,proto3" json:"buildTime,omitempty"` // @gotags: json:"buildTime,omitempty"
}

func (x *ServicesInfo) Reset() {
	*x = ServicesInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ServicesInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServicesInfo) ProtoMessage() {}

func (x *ServicesInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServicesInfo.ProtoReflect.Descriptor instead.
func (*ServicesInfo) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{5}
}

func (x *ServicesInfo) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *ServicesInfo) GetGitCommit() string {
	if x != nil {
		return x.GitCommit
	}
	return ""
}

func (x *ServicesInfo) GetGoVersion() string {
	if x != nil {
		return x.GoVersion
	}
	return ""
}

func (x *ServicesInfo) GetCompiler() string {
	if x != nil {
		return x.Compiler
	}
	return ""
}

func (x *ServicesInfo) GetBuildTime() string {
	if x != nil {
		return x.BuildTime
	}
	return ""
}

type Services struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServicesInfo *ServicesInfo `protobuf:"bytes,6,opt,name=ServicesInfo,proto3" json:"servicesInfo,omitempty"` // @gotags: json:"servicesInfo,omitempty"
}

func (x *Services) Reset() {
	*x = Services{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Services) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Services) ProtoMessage() {}

func (x *Services) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Services.ProtoReflect.Descriptor instead.
func (*Services) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{6}
}

func (x *Services) GetServicesInfo() *ServicesInfo {
	if x != nil {
		return x.ServicesInfo
	}
	return nil
}

type RouterListener struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty" yaml:"name" validate:"required" gorm:"column:name;primaryKey" mapstructure:"name"`      // @gotags: yaml:"name" validate:"required" gorm:"column:name;primaryKey" mapstructure:"name"
	Pem    string `protobuf:"bytes,2,opt,name=Pem,proto3" json:"Pem,omitempty" yaml:"pem" gorm:"column:pem" mapstructure:"pem"`        // @gotags: yaml:"pem"  gorm:"column:pem" mapstructure:"pem"
	Port   int32  `protobuf:"varint,3,opt,name=Port,proto3" json:"Port,omitempty" yaml:"port" validate:"required,min=1,max=65535" gorm:"column:port" mapstructure:"port"`     // @gotags: yaml:"port" validate:"required,min=1,max=65535" gorm:"column:port" mapstructure:"port"
	Listen string `protobuf:"bytes,4,opt,name=Listen,proto3" json:"Listen,omitempty" yaml:"listen" validate:"required,hostname_rfc1123" gorm:"column:listen" mapstructure:"listen"`  // @gotags: yaml:"listen" validate:"required,hostname_rfc1123" gorm:"column:listen" mapstructure:"listen"
	Secure bool   `protobuf:"varint,5,opt,name=Secure,proto3" json:"Secure,omitempty" yaml:"secure" gorm:"column:secure" mapstructure:"secure"` // @gotags: yaml:"secure" gorm:"column:secure" mapstructure:"secure"
}

func (x *RouterListener) Reset() {
	*x = RouterListener{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_modules_listener_listener_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RouterListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RouterListener) ProtoMessage() {}

func (x *RouterListener) ProtoReflect() protoreflect.Message {
	mi := &file_proto_modules_listener_listener_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RouterListener.ProtoReflect.Descriptor instead.
func (*RouterListener) Descriptor() ([]byte, []int) {
	return file_proto_modules_listener_listener_proto_rawDescGZIP(), []int{7}
}

func (x *RouterListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RouterListener) GetPem() string {
	if x != nil {
		return x.Pem
	}
	return ""
}

func (x *RouterListener) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *RouterListener) GetListen() string {
	if x != nil {
		return x.Listen
	}
	return ""
}

func (x *RouterListener) GetSecure() bool {
	if x != nil {
		return x.Secure
	}
	return false
}

var File_proto_modules_listener_listener_proto protoreflect.FileDescriptor

var file_proto_modules_listener_listener_proto_rawDesc = []byte{
	0x0a, 0x25, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x22, 0x0d, 0x0a, 0x0b, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x22, 0x41, 0x0a, 0x10, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x2d, 0x0a, 0x05, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x05, 0x49, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x4f, 0x0a, 0x11, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x53, 0x65, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x53, 0x65, 0x6e, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x52, 0x65, 0x63, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x52, 0x65, 0x63, 0x76, 0x22, 0xb9, 0x02, 0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x46, 0x75, 0x6c, 0x6c,
	0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x46, 0x75,
	0x6c, 0x6c, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x31, 0x0a, 0x05, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e,
	0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x46, 0x75, 0x6e, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x05, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x33, 0x0a, 0x06, 0x4f,
	0x75, 0x74, 0x70, 0x75, 0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x22, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x12, 0x22, 0x0a, 0x0c, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x43, 0x6c, 0x69, 0x65,
	0x6e, 0x74, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x74,
	0x6f, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0e, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65,
	0x22, 0x57, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x16, 0x0a,
	0x06, 0x45, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x45,
	0x6e, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x44, 0x72, 0x69, 0x76, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x22, 0x9e, 0x01, 0x0a, 0x0c, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d, 0x69,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x69, 0x74, 0x43, 0x6f, 0x6d, 0x6d,
	0x69, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x47, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x47, 0x6f, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x43, 0x6f, 0x6d, 0x70, 0x69, 0x6c, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x42, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x42, 0x75, 0x69, 0x6c, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x46, 0x0a, 0x08, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x3a, 0x0a, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6c,
	0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x49, 0x6e,
	0x66, 0x6f, 0x22, 0x7a, 0x0a, 0x0e, 0x52, 0x6f, 0x75, 0x74, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74,
	0x65, 0x6e, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x50, 0x65, 0x6d, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x50, 0x65, 0x6d, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x6f,
	0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x53, 0x65, 0x63, 0x75, 0x72, 0x65, 0x32, 0x4b,
	0x0a, 0x08, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x12, 0x3f, 0x0a, 0x08, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x15, 0x2e, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65,
	0x72, 0x2e, 0x4e, 0x6f, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x1a, 0x1a, 0x2e,
	0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x32, 0x5a, 0x30, 0x66,
	0x61, 0x6c, 0x74, 0x61, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x73, 0x2f, 0x6c, 0x69,
	0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x3b, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_modules_listener_listener_proto_rawDescOnce sync.Once
	file_proto_modules_listener_listener_proto_rawDescData = file_proto_modules_listener_listener_proto_rawDesc
)

func file_proto_modules_listener_listener_proto_rawDescGZIP() []byte {
	file_proto_modules_listener_listener_proto_rawDescOnce.Do(func() {
		file_proto_modules_listener_listener_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_modules_listener_listener_proto_rawDescData)
	})
	return file_proto_modules_listener_listener_proto_rawDescData
}

var file_proto_modules_listener_listener_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_modules_listener_listener_proto_goTypes = []interface{}{
	(*NoParameter)(nil),       // 0: listener.NoParameter
	(*ServicesResponse)(nil),  // 1: listener.ServicesResponse
	(*ParameterFunction)(nil), // 2: listener.ParameterFunction
	(*ServicesItems)(nil),     // 3: listener.ServicesItems
	(*Discovery)(nil),         // 4: listener.Discovery
	(*ServicesInfo)(nil),      // 5: listener.ServicesInfo
	(*Services)(nil),          // 6: listener.Services
	(*RouterListener)(nil),    // 7: listener.RouterListener
}
var file_proto_modules_listener_listener_proto_depIdxs = []int32{
	3, // 0: listener.ServicesResponse.Items:type_name -> listener.ServicesItems
	2, // 1: listener.ServicesItems.Input:type_name -> listener.ParameterFunction
	2, // 2: listener.ServicesItems.Output:type_name -> listener.ParameterFunction
	5, // 3: listener.Services.ServicesInfo:type_name -> listener.ServicesInfo
	0, // 4: listener.Listener.Services:input_type -> listener.NoParameter
	1, // 5: listener.Listener.Services:output_type -> listener.ServicesResponse
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_modules_listener_listener_proto_init() }
func file_proto_modules_listener_listener_proto_init() {
	if File_proto_modules_listener_listener_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_modules_listener_listener_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ParameterFunction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesItems); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Discovery); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ServicesInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Services); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_modules_listener_listener_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RouterListener); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_modules_listener_listener_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_modules_listener_listener_proto_goTypes,
		DependencyIndexes: file_proto_modules_listener_listener_proto_depIdxs,
		MessageInfos:      file_proto_modules_listener_listener_proto_msgTypes,
	}.Build()
	File_proto_modules_listener_listener_proto = out.File
	file_proto_modules_listener_listener_proto_rawDesc = nil
	file_proto_modules_listener_listener_proto_goTypes = nil
	file_proto_modules_listener_listener_proto_depIdxs = nil
}
