// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/services/game/ground.proto

package game

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetListGround struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ground []*Ground `protobuf:"bytes,1,rep,name=Ground,proto3" json:"Ground,omitempty"`
}

func (x *GetListGround) Reset() {
	*x = GetListGround{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_game_ground_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetListGround) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListGround) ProtoMessage() {}

func (x *GetListGround) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_game_ground_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListGround.ProtoReflect.Descriptor instead.
func (*GetListGround) Descriptor() ([]byte, []int) {
	return file_proto_services_game_ground_proto_rawDescGZIP(), []int{0}
}

func (x *GetListGround) GetGround() []*Ground {
	if x != nil {
		return x.Ground
	}
	return nil
}

type Ground struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID               string `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	TypeID           string `protobuf:"bytes,2,opt,name=TypeID,proto3" json:"TypeID,omitempty"`
	Name             string `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Location         string `protobuf:"bytes,4,opt,name=Location,proto3" json:"Location,omitempty"`
	LocationMetadata string `protobuf:"bytes,5,opt,name=LocationMetadata,proto3" json:"LocationMetadata,omitempty"`
	ModifiedBy       string `protobuf:"bytes,6,opt,name=ModifiedBy,proto3" json:"ModifiedBy,omitempty"`
	Metadata         string `protobuf:"bytes,7,opt,name=Metadata,proto3" json:"Metadata,omitempty"`
	CreatedAt        string `protobuf:"bytes,8,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	UpdatedAt        string `protobuf:"bytes,9,opt,name=UpdatedAt,proto3" json:"UpdatedAt,omitempty"`
}

func (x *Ground) Reset() {
	*x = Ground{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_services_game_ground_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ground) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ground) ProtoMessage() {}

func (x *Ground) ProtoReflect() protoreflect.Message {
	mi := &file_proto_services_game_ground_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ground.ProtoReflect.Descriptor instead.
func (*Ground) Descriptor() ([]byte, []int) {
	return file_proto_services_game_ground_proto_rawDescGZIP(), []int{1}
}

func (x *Ground) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Ground) GetTypeID() string {
	if x != nil {
		return x.TypeID
	}
	return ""
}

func (x *Ground) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Ground) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Ground) GetLocationMetadata() string {
	if x != nil {
		return x.LocationMetadata
	}
	return ""
}

func (x *Ground) GetModifiedBy() string {
	if x != nil {
		return x.ModifiedBy
	}
	return ""
}

func (x *Ground) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

func (x *Ground) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

func (x *Ground) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

var File_proto_services_game_ground_proto protoreflect.FileDescriptor

var file_proto_services_game_ground_proto_rawDesc = []byte{
	0x0a, 0x20, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2f, 0x67, 0x61, 0x6d, 0x65, 0x2f, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x24, 0x0a, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x47, 0x72,
	0x6f, 0x75, 0x6e, 0x64, 0x52, 0x06, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x22, 0x84, 0x02, 0x0a,
	0x06, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x54, 0x79, 0x70, 0x65, 0x49,
	0x44, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x79, 0x70, 0x65, 0x49, 0x44, 0x12,
	0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x4e,
	0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x2a, 0x0a, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x4c, 0x6f, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1e, 0x0a, 0x0a, 0x4d,
	0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x4d, 0x6f, 0x64, 0x69, 0x66, 0x69, 0x65, 0x64, 0x42, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64,
	0x41, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x32, 0x47, 0x0a, 0x0b, 0x47, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x13, 0x2e, 0x70, 0x6f, 0x73, 0x74, 0x2e, 0x47,
	0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x47, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x42, 0x2b, 0x5a, 0x29,
	0x66, 0x61, 0x6c, 0x74, 0x61, 0x72, 0x2d, 0x6d, 0x6f, 0x64, 0x75, 0x6c, 0x65, 0x2d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f,
	0x67, 0x61, 0x6d, 0x65, 0x3b, 0x67, 0x61, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_proto_services_game_ground_proto_rawDescOnce sync.Once
	file_proto_services_game_ground_proto_rawDescData = file_proto_services_game_ground_proto_rawDesc
)

func file_proto_services_game_ground_proto_rawDescGZIP() []byte {
	file_proto_services_game_ground_proto_rawDescOnce.Do(func() {
		file_proto_services_game_ground_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_services_game_ground_proto_rawDescData)
	})
	return file_proto_services_game_ground_proto_rawDescData
}

var file_proto_services_game_ground_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_services_game_ground_proto_goTypes = []interface{}{
	(*GetListGround)(nil), // 0: post.GetListGround
	(*Ground)(nil),        // 1: post.Ground
	(*emptypb.Empty)(nil), // 2: google.protobuf.Empty
}
var file_proto_services_game_ground_proto_depIdxs = []int32{
	1, // 0: post.GetListGround.Ground:type_name -> post.Ground
	2, // 1: post.GameService.GetGround:input_type -> google.protobuf.Empty
	0, // 2: post.GameService.GetGround:output_type -> post.GetListGround
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_services_game_ground_proto_init() }
func file_proto_services_game_ground_proto_init() {
	if File_proto_services_game_ground_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_services_game_ground_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetListGround); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_services_game_ground_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ground); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_services_game_ground_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_services_game_ground_proto_goTypes,
		DependencyIndexes: file_proto_services_game_ground_proto_depIdxs,
		MessageInfos:      file_proto_services_game_ground_proto_msgTypes,
	}.Build()
	File_proto_services_game_ground_proto = out.File
	file_proto_services_game_ground_proto_rawDesc = nil
	file_proto_services_game_ground_proto_goTypes = nil
	file_proto_services_game_ground_proto_depIdxs = nil
}
